version = 0.1

[default.deploy.parameters]
stack_name = "demo-dqsl"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "demo-dqsl"
region = "us-east-1"
parameter_overrides = "ClusterId=\"siabt3etsijuyijmtlu2nw6scy\" DataBucket=\"dqsl-demo-data-londoso\""
image_repositories = []